### ISSUE TITLE
thrust::merge_by_key CUDA 9.1 compilation issue

### ISSUE THREAD

**Issue by swittmer** [thrust/thrust#911]
Hi,

this sample code compiles in CUDA 8.0 but fails to compile in CUDA 9.1.

```
#include <thrust/sort.h>
#include <thrust/device_ptr.h>
int main() {
	const int N = 100;
	thrust::device_ptr<int> input_key_A1;
	thrust::device_ptr<float> input_val_A1;
	thrust::device_ptr<int> input_key_B1;
	thrust::device_ptr<float> input_val_B1;
	thrust::device_ptr<int> output_key;
	thrust::device_ptr<float> output_val;

	// use key tuples (with one element to keep it simple)
	auto input_key_tuple_A = thrust::make_tuple(input_key_A1);
	auto input_key_tuple_B = thrust::make_tuple(input_key_B1);
	auto output_key_tuple = thrust::make_tuple(output_key);
	// use zip iterator to zip together elements of a tuple (each is an iterator)
	auto zip_it_A = thrust::make_zip_iterator(input_key_tuple_A);
	auto zip_it_B = thrust::make_zip_iterator(input_key_tuple_B);
	auto zip_it_out = thrust::make_zip_iterator(output_key_tuple);

	// does NOT compile in CUDA 9.1 (compiles fine in CUDA 8)
	thrust::merge_by_key(zip_it_A, zip_it_A + N, zip_it_B, zip_it_B + N, input_val_A1, input_val_B1, zip_it_out, output_val);

	return 0;
}
```

called by: ./nvcc ~/Desktop/mergetest.cu --std=c++11
gives following error:

```
./..//include/thrust/system/cuda/detail/merge.h(73): error: function "thrust::less<T>::operator() [with T=float]" cannot be called with the given argument list
            argument types are: (key2_type, key1_type)
            object type is: thrust::less<float>
...
```

I assume it is a bug, because there should be no need to perform any comparisons on the values.

Environment: CentOS 7.4, CUDA 9.1. Also reproducible in VS 2017 using toolset 14.11.

**Comment by brycelelbach** [comment]
Sounds like a bug, yes. May be a dupe of another merge_by_key bug with zip iterators.

No promises on when I'll be able to look at this; probably not until late June at the earliest.

**Comment by swittmer** [comment]
Thanks for info. Could you please comment on my workaround of explicitly using thrust::less<thrust::tuple<int, int>>() as Comparer. Do you think it is safe?

**Comment by brycelelbach** [comment]
That will probably make the code slower; thrust::less<int> (or any builtin type) is special cased and goes to an optimized backend. That is probably fine as a workaround safety wise, but may be slow.

**Comment by brycelelbach** [comment]
The issue was that the overload of merge_by_key in the CUDA backend that didn't take a comparison used `thrust::less<item_type>` instead of `thrust::less<key_type>`.

**Comment by brycelelbach** [comment]
NVBug 2166653

**Comment by brycelelbach** [comment]
Wow, how did our tests not catch this.

**Comment by swittmer** [comment]
So this did not get fixed in CUDA 10, right?

**Comment by swittmer** [comment]
Thanks for the fix, it compiles fine again in CUDA 10.1.
