### ISSUE TITLE
thrust::reduce_by_key() problem

### ISSUE THREAD

**Issue by newstzpz** [thrust/thrust#639]
The following code will fail to compile in VS 2013.

int *A, *B, *C, *D, N;
auto new_end = thrust::reduce_by_key(thrust::device, A, A + N, B, C, D);

**Comment by jaredhoberock** [comment]
Thanks for the report. What is the compiler error message?

**Comment by newstzpz** [comment]
The error message is:

1>C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v6.5\include\thrust/iterator/detail/permutation_iterator_base.h(44): error : class "thrust::detail::minimum_system<thrust::host_system_tag, thrust::system::cuda::detail::par_t, thrust::detail::minimum_type_detail::any_conversion, thrust::detail::minimum_type_detail::any_conversion, thrust::detail::minimum_type_detail::any_conversion, thrust::detail::minimum_type_detail::any_conversion, thrust::detail::minimum_type_detail::any_conversion, thrust::detail::minimum_type_detail::any_conversion, thrust::detail::minimum_type_detail::any_conversion, thrust::detail::minimum_type_detail::any_conversion, thrust::detail::minimum_type_detail::any_conversion, thrust::detail::minimum_type_detail::any_conversion, thrust::detail::minimum_type_detail::any_conversion, thrust::detail::minimum_type_detail::any_conversion, thrust::detail::minimum_type_detail::any_conversion, thrust::detail::minimum_type_detail::any_conversion>" has no member "type"

1>C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v6.5\include\thrust/iterator/detail/zip_iterator_base.h(141): error : class "thrust::detail::tuple_impl_specific::apply2<thrust::detail::minimum_system_lambda, <error-type>, thrust::any_system_tag>" has no member "type"

1>C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v6.5\include\thrust/iterator/detail/zip_iterator_base.h(141): error : class "thrust::detail::tuple_impl_specific::apply2<thrust::detail::minimum_system_lambda, thrust::system::cuda::detail::par_t, <error-type>>" has no member "type"

1>C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v6.5\include\thrust/iterator/detail/zip_iterator_base.h(141): error : class "thrust::detail::tuple_impl_specific::apply2<thrust::detail::minimum_system_lambda, thrust::system::cuda::detail::par_t, <error-type>>" has no member "type"

**Comment by jaredhoberock** [comment]
Thanks for posting the error message. I can reproduce the error in Thrust v1.7.2, but not in Thrust v1.8.0 or the latest development version of Thrust.

Could you try again with Thrust 1.8.0 and see if that eliminates the issue?

**Comment by newstzpz** [comment]
Yes, it works in Thrust v1.8.0. Thanks!
