### ISSUE TITLE
cuda_runtime_api.h required even if not using CUDA

### ISSUE THREAD

**Issue by slayoo** [thrust/thrust#386]
Tested with the current git version:

```
$ cat test.cpp 
#include <thrust/host_vector.h>
int main(){
        return 0;
}
```

```
$ clang++ test.cpp 
In file included from test.cpp:1:
In file included from /usr/include/thrust/host_vector.h:26:
In file included from /usr/include/thrust/detail/vector_base.h:29:
In file included from /usr/include/thrust/detail/contiguous_storage.h:155:
In file included from /usr/include/thrust/detail/contiguous_storage.inl:22:
In file included from /usr/include/thrust/detail/allocator/copy_construct_range.h:46:
In file included from /usr/include/thrust/detail/allocator/copy_construct_range.inl:21:
In file included from /usr/include/thrust/detail/copy.h:90:
In file included from /usr/include/thrust/detail/copy.inl:21:
In file included from /usr/include/thrust/system/detail/generic/copy.h:58:
In file included from /usr/include/thrust/system/detail/generic/copy.inl:23:
In file included from /usr/include/thrust/transform.h:724:
In file included from /usr/include/thrust/detail/transform.inl:25:
In file included from /usr/include/thrust/system/detail/generic/transform.h:105:
In file included from /usr/include/thrust/system/detail/generic/transform.inl:19:
In file included from /usr/include/thrust/for_each.h:279:
In file included from /usr/include/thrust/detail/for_each.inl:27:
In file included from /usr/include/thrust/system/detail/adl/for_each.h:32:
In file included from /usr/include/thrust/system/cuda/detail/for_each.h:59:
In file included from /usr/include/thrust/system/cuda/detail/for_each.inl:29:
In file included from /usr/include/thrust/system/cuda/detail/detail/launch_closure.h:113:
In file included from /usr/include/thrust/system/cuda/detail/detail/launch_closure.inl:19:
In file included from /usr/include/thrust/detail/temporary_array.h:27:
In file included from /usr/include/thrust/detail/allocator/temporary_allocator.h:23:
In file included from /usr/include/thrust/memory.h:25:
In file included from /usr/include/thrust/detail/reference.h:166:
In file included from /usr/include/thrust/detail/reference.inl:22:
In file included from /usr/include/thrust/system/detail/generic/memory.h:71:
In file included from /usr/include/thrust/system/detail/generic/memory.inl:21:
In file included from /usr/include/thrust/system/detail/adl/malloc_and_free.h:32:
In file included from /usr/include/thrust/system/cuda/detail/malloc_and_free.h:22:
/usr/include/thrust/system/cuda/detail/guarded_cuda_runtime_api.h:38:10: fatal error: 'cuda_runtime_api.h' file not found
#include <cuda_runtime_api.h>
         ^
1 error generated.
```

HTH,
Sylwester

**Comment by slayoo** [comment]
I've just checked and got the same behaviour with both current snapshot from the repository as well as Thrust 1.8.0.

However, this one:

    #define THRUST_DEVICE_SYSTEM THRUST_DEVICE_SYSTEM_CPP
    #include <thrust/system/cpp/vector.h>
    int main(){
            return 0;
    }

works on Thrust 1.8.0 (Debian package) while it does not work with the version from the repo... any ideas?

**Comment by slayoo** [comment]
The change in behaviour (regression?) seem to be cause by a new preprocessor include introduced three days ago:

https://github.com/thrust/thrust/commit/63fe36d8ed897651a885590767459f6e97f8d28b#diff-a91e23482848b7e11f580eeb2a08b772R20

**Comment by jaredhoberock** [comment]
Thanks @slayoo, could you check if the commit to jaredhoberock/thrust branch issue-386 fixes the regression for you?

**Comment by slayoo** [comment]
Yes it does! Thank you!
Sylwester

**Comment by jeffhammond** [comment]
This is still broken.  It is really hard to write Thrust code on an airplane using a Mac laptop when NVCC is required to compile CPU code 😞 
```
$ g++-8 -std=c++17 -O0 -g3 -Wall -I/Users/x/Work/NVIDIA/thrust test.cpp 
In file included from /Users/x/Work/NVIDIA/thrust/thrust/type_traits/is_trivially_relocatable.h:162,
                 from /Users/x/Work/NVIDIA/thrust/thrust/system/detail/sequential/copy.inl:24,
                 from /Users/x/Work/NVIDIA/thrust/thrust/system/detail/sequential/copy.h:62,
                 from /Users/x/Work/NVIDIA/thrust/thrust/system/detail/adl/copy.h:25,
                 from /Users/x/Work/NVIDIA/thrust/thrust/detail/copy.inl:22,
                 from /Users/x/Work/NVIDIA/thrust/thrust/detail/copy.h:90,
                 from /Users/x/Work/NVIDIA/thrust/thrust/detail/allocator/copy_construct_range.inl:21,
                 from /Users/x/Work/NVIDIA/thrust/thrust/detail/allocator/copy_construct_range.h:46,
                 from /Users/x/Work/NVIDIA/thrust/thrust/detail/contiguous_storage.inl:22,
                 from /Users/x/Work/NVIDIA/thrust/thrust/detail/contiguous_storage.h:240,
                 from /Users/x/Work/NVIDIA/thrust/thrust/detail/vector_base.h:29,
                 from /Users/x/Work/NVIDIA/thrust/thrust/host_vector.h:26,
                 from test.cpp:1:
/Users/x/Work/NVIDIA/thrust/thrust/system/cuda/detail/guarded_cuda_runtime_api.h:38:10: fatal error: cuda_runtime_api.h: No such file or directory
 #include <cuda_runtime_api.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

```
$ cat test.cpp 
#include <thrust/host_vector.h>
int main(){
        return 0;
}
```

**Comment by slayoo** [comment]
As per @jaredhoberock's comment here: https://github.com/thrust/thrust/issues/383#issuecomment-44785631

it seems to be needed to define:
```
#define THRUST_DEVICE_SYSTEM THRUST_DEVICE_SYSTEM_CPP
```
before #including thrust headers
